[package]
name = "rust-cloud-run"
version = "0.1.0"
authors = ["Moritz Eck <moritz.eck@gmail.com>"]
edition = "2018"

[[bin]]
name = "runner"
path = "src/main.rs"

[dependencies]
actix-web = "3"

[dev-dependencies]
actix-rt = "2"
