name: build and test

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: install latest stable rust version
        uses: actions-rs/toolchain@v1
      - name: build crate
        run: cargo build --verbose --release
      - name: test crate
        run: cargo test --verbose --no-fail-fast --release